### ISSUE TITLE
Failed to construct window after upgrading `pyside6==6.6.1` to `pyside6==6.7.1`

### ISSUE THREAD

**Issue by jkjkil4** [jkjkil4/JAnim#4]
```
> janim examples
1: HelloJAnimExample
2: SimpleCurveExample
3: TextExample
4: TypstExample
5: AnimatingPiExample
6: NumberPlaneExample
7: UpdaterExample

That module has multiple timelines, which ones would you like to render?
Timeline Name or Number: 1
Traceback (most recent call last):
  File "signature_bootstrap.py", line 77, in bootstrap
  File "signature_bootstrap.py", line 93, in find_incarnated_files
  File "C:\Program Files\Python312\Lib\pathlib.py", line 1162, in __init__
    super().__init__(*args)
  File "C:\Program Files\Python312\Lib\pathlib.py", line 373, in __init__
    raise TypeError(
TypeError: argument should be a str or an os.PathLike object where __fspath__ returns 
a str, not 'NoneType'
Fatal Python error: could not initialize part 2
Python runtime state: initialized

Current thread 0x000058a4 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1288 in create_module
  File "<frozen importlib._bootstrap>", line 813 in module_from_spec
  File "<frozen importlib._bootstrap>", line 921 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1415 in _handle_fromlist
  File "C:\Users\jkjki\AppData\Roaming\Python\Python312\site-packages\PySide6\__init__.py", line 64 in _setupQtDirectories
  File "C:\Users\jkjki\AppData\Roaming\Python\Python312\site-packages\PySide6\__init__.py", line 124 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 994 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "D:\Projects\janim\src\janim\gui\anim_viewer.py", line 2 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 994 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "D:\Projects\janim\src\janim\cli.py", line 26 in run
  File "D:\Projects\janim\src\janim\__main__.py", line 113 in run
  File "D:\Projects\janim\src\janim\__main__.py", line 32 in main
  File "C:\Users\jkjki\AppData\Roaming\Python\Python312\Scripts\janim.exe\__main__.py", line 7 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main

Extension modules: _wmi, moderngl.mgl, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, PIL._imaging, fontTools.cu2qu.cu2qu, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._isolve._iterative, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.linalg._flinalg, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.special._ufuncs_cxx, scipy.special._ufuncs, 
scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial.transform._rotation, psutil._psutil_windows, pathops._pathops, shiboken6.Shiboken (total: 57)
```

**Comment by jkjkil4** [comment]
Seems like it is caused by `shiboken6`.

You can run the following commands to solve this problem manually.

```sh
pip uninstall shiboken6
pip install shiboken6
```

If it still doesn't work, leave comments below.

Related issues:
- https://bugreports.qt.io/browse/PYSIDE-2616
- https://bugreports.qt.io/browse/PYSIDE-2650
